// vue-movie-searcher/src/components/Movie.vue
<template>
  <div class="movie">
    <h2>{{ movie.Title }}</h2>
    <div>
      <img width="200" :alt="altText" :src="movie.Poster" />
    </div>
    <p>{{ movie.Year }}</p>
  </div>
</template>

<script>
  import { computed } from 'vue';
  export default {
    name: "Movie",
    props: ['movie'],
    setup({ movie }) {
      const altText = computed(() => `The movie titled: ${movie.Title}`);
      return { altText };
    }
  };
</script>

// react-movie-searcher/components/Movie.jsx
import React from "react";

export default function Movie(props) {
  return (
    <div className="movie">
      <h2>{props.title}</h2>
      <div>
        <img
          width="200"
          alt={`The movie titled: ${props.title}`}
          src={props.poster}
        />
      </div>
      <p>{props.year}</p>
    </div>
  );
}
