// react-movie-searcher/components/Search.jsx
import React from 'react';

export default function Search({movieTitle, handleSubmit, handleChange}) {
  return (
    <form className="search">
      <input
        type="text"
        value={movieTitle}
        onChange={handleChange}
      />
      <input onClick={handleSubmit} type="submit" value="SEARCH" />
    </form>
  )
}

// vue-movie-searcher/src/components/Search.vue
<template>
  <form class="search">
    <input
       type="text"
       :value="movieTitle"
       @keyup="handleChange"
    />
    <input @click="handleSubmit" type="submit" value="SEARCH" />
  </form>
</template>

<script>
  import { ref } from 'vue';
  export default {
    name: 'Search',
    props: ['search'],
    setup({ search }, { emit }) {
      const movieTitle = ref(search);
      return {
        movieTitle,
        handleSubmit(event) {
          event.preventDefault();
          emit('search', movieTitle.value);
        },
        handleChange(event) {
          movieTitle.value = event.target.value
        }
      }
    }
  };
</script>
